### ISSUE TITLE
Any way to import PyWal colors into the CSS?

### ISSUE THREAD

**Issue by TheElevatedOne** [nwg-piotr/nwg-drawer#155]
I am trying to use this drawer for my Hyprland rice and I am trying to use PyWal for simpler coloring using Wallpapers.

I am looking at the GTK 3.0 CSS Docs and I am trying to, well `@import url("/home/the-elevated-one/.cache/wal/colors.css");` and it errors out with:
```
ERRO[0000] ERROR: /home/the-elevated-one/.config/nwg-drawer/drawer.css css file not found or erroneous. Using GTK styling. 
FATA[0000] Unable to create window:colors.css:3:1Invalid name of pseudo-class 
```

What am I doing wrong? How can I fix this?

**Comment by nwg-piotr** [comment]
I have no idea what PyWal generates, but nothing useful with nwg-drawer for sure. Open one of css files in ~/.config/nwg-drawer/ and check which css selectors are supported.

**Comment by TheElevatedOne** [comment]
PyWal generates config files for colors from the current wallpaper.

For my current wallpaper, the generated CSS looks like this:
```css
/* CSS variables
   Generated by 'wal' */
:root {
    --wallpaper: url("/home/the-elevated-one/Pictures/Wallpapers/orion-what-the-hell.jpg");

    /* Special */
    --background: #0c0a0c;
    --foreground: #b0bccc;
    --cursor: #b0bccc;

    /* Colors */
    --color0: #0c0a0c;
    --color1: #5F4D67;
    --color2: #8F5473;
    --color3: #33688F;
    --color4: #6D688F;
    --color5: #996D93;
    --color6: #CF6A9D;
    --color7: #b0bccc;
    --color8: #7b838e;
    --color9: #5F4D67;
    --color10: #8F5473;
    --color11: #33688F;
    --color12: #6D688F;
    --color13: #996D93;
    --color14: #CF6A9D;
    --color15: #b0bccc;
}
```

So I am just wondering that, as nwg-drawer uses GTK3 and CSS for styling if there was a way to import that file and use the generated colors, to have the theme seemless.

The GTK3 CSS docs that I was talking about: https://docs.gtk.org/gtk3/css-overview.html#importing-style-sheets
