### ISSUE TITLE
window opacity

### ISSUE THREAD

**Issue by PowaBanga** [nwg-piotr/nwg-drawer#156]
Hi,
I am on archlinux, with openbox.
Is it possible to set some opacity to the window of nwg-drawer, How ?

Regards,
Powabanga

**Comment by nwg-piotr** [comment]
Normally you define it in `~/.config/drawer.css` (or any other style sheet you use):

```css
window {
    background-color: rgba (36, 47, 79, 0.95);
}
```

But openbox does not support window transparency. Possibly some compositor would help, but you need to ask Google. I stopped using openbox years ago.
