### ISSUE TITLE
Catergory Buttons Styling Does Not Work

### ISSUE THREAD

**Issue by OdiousImp2604** [nwg-piotr/nwg-drawer#6]
The styling for category buttons does not work. The buttons continue to take the styling from the buttons.
`
nwg-drawer version 0.1.3`

DRAWER.CSS
```
window {
    background-color: rgba (36, 47, 79, 0.95);
    color: #eeeeee
}

entry {
   box-shadow: 0 0 6 5 #2e3440;
   background-color: #3b4252;
   border: none;
   border-radius:10px;
}

button {
    box-shadow: 0 0 6 5 #2e3440;
    background-color: #3b4252;
    border: none;
    border-radius:5px;
    margin: 4px;
}

category-button {
    background-color: transparent;
    padding: 1px;
}    
    

button:hover {
    background-color: rgba(129,161,193,0.7);
}

button:focus {
    background-color: #5e81ac;
}

#pinned-box {
    padding-bottom: 10px;
    border-bottom: 1px dotted gray
}

#files-box {
    padding: 10px;
    border: 1px dotted gray;
}    

```

**Comment by nwg-piotr** [comment]
You missed `#`. Should be:

```css
#category-button {
    background-color: transparent;
    padding: 1px;
}
```

**Comment by OdiousImp2604** [comment]
No change.

**Comment by nwg-piotr** [comment]
Works well for me. BTW: you should also use use `px` in lines 7 and 14.

```css
window {
    background-color: rgba (36, 47, 79, 0.95);
    color: #eeeeee
}

entry {
   box-shadow: 0 0 6px 5px #2e3440;
   background-color: #3b4252;
   border: none;
   border-radius:10px;
}

button {
    box-shadow: 0 0 6px 5px #2e3440;
    background-color: #3b4252;
    border: none;
    border-radius:5px;
    margin: 4px;
}

#category-button {
    background-color: transparent;
    padding: 1px;
}    
    

button:hover {
    background-color: rgba(129,161,193,0.7);
}

button:focus {
    background-color: #5e81ac;
}

#pinned-box {
    padding-bottom: 10px;
    border-bottom: 1px dotted gray
}

#files-box {
    padding: 10px;
    border: 1px dotted gray;
}
```

![2021-07-11-235512_screenshot](https://user-images.githubusercontent.com/20579136/125211103-43816700-e2a4-11eb-801c-01e1418b4dcb.png)
